apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-pod
  template:
    metadata:
      labels:
        app: user-pod
    spec:
      restartPolicy: Always
      containers:
      - image: jeralsandeeptha/url-shortner-user-service-main:eb6b49fc6ed157b913ec510b644c8a9cac9719d6
        name: users-service
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "5001"
        - name: NODE_ENV
          value: "production"
        - name: KEYCLOACK_SERVER_URL
          value: "http://keycloak-service:8070"
        - name: KEYCLOACK_GATEWAY_SERVER_URL
          value: "https://api.lumenlink.com/auth"
        - name: KEYCLOACK_CLIENT_ID
          value: "url-shortner-user-service"
        - name: KEYCLOACK_CLIENT_SECRET
          value: "Sq5tI8x7JpIKoXijO4jQ9XoIdhGFKNPb"
        - name: DATABASE_URL
          value: "postgresql://jeral:1234@user-db-service:5431/users_db"
        - name: BASE_URL
          value: "https://lumenlink.com"
        - name: DOMAIN
          value: ".lumenlink.com"
        ports:
        - containerPort: 5001
        command: ["sh", "-c"]
        args:
          - |
            npx prisma migrate deploy
            npm run start
