apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mongodb-deployment
  labels:
    app:  mongodb-pod
spec:
  selector:
    matchLabels:
      app: mongodb-pod
  replicas: 1
  template:
    metadata:
      labels:
        app:  mongodb-pod
    spec:
      containers:
      - name:  mongodb-service-container
        image:  mongo:latest
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: 'jeral'
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: '1234'
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-volume
          mountPath: /data/db
      volumes:
        - name: mongodb-volume
          persistentVolumeClaim:
            claimName: mongodb-pvc
      restartPolicy: Always
