apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-db-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /mnt/data/user_db_data
