apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express-pod
  template:
    metadata:
      labels:
        app: mongo-express-pod
    spec:
      containers:
      - image: mongo-express:latest
        name: mongo-express-container
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: jeral
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: "1234"
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongodb-service
        - name: ME_CONFIG_MONGODB_AUTH_DATABASE
          value: admin
        - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
          value: "true"
        - name: ME_CONFIG_BASICAUTH_USERNAME
          value: yohan
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          value: "1234"
        ports:
        - containerPort: 8081
        volumeMounts:
        - mountPath: /config
          name: mongo-express-volume
      volumes:
        - name: mongo-express-volume
          persistentVolumeClaim:
            claimName: mongo-express-pvc
