apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  labels:
    app:  pgadmin-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin-pod
  template:
    metadata:
      labels:
        app: pgadmin-pod
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ['sh', '-c', 'mkdir -p /var/lib/pgadmin/sessions && chmod -R 777 /var/lib/pgadmin']
          volumeMounts:
            - name: pgadmin-volume
              mountPath: /var/lib/pgadmin
      containers:
        - image: elestio/pgadmin:latest
          name: pgadmin-container
          ports:
            - containerPort: 5433
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: jeral@gmail.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "1234"
            - name: PGADMIN_LISTEN_PORT
              value: "5433"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: pgadmin-volume
              mountPath: /var/lib/pgadmin
      volumes:
        - name: pgadmin-volume
          persistentVolumeClaim:
            claimName: pgadmin-pvc