apiVersion: apps/v1
kind: Deployment
metadata:
  name:  frontend-deployment
  labels:
    app:  frontend-pod
spec:
  selector:
    matchLabels:
      app: frontend-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-pod
    spec:
      containers:
      - name: frontend-service-container
        image: jeralsandeeptha/url-shortner-frontend-service-main:b21019fcbfad594ceb53a1ea27413769feb55987
        ports:
          - containerPort: 80
        env: 
          - name: MODE
            value: production
          - name: VITE_API_URL
            value: https://api.lumenlink.com
          - name: VITE_DOMAIN
            value: https://lumenlink.com
        restartPolicy: always